apiVersion: apps/v1
kind: Deployment
metadata:
  name: enyew
  labels:
    app: mywebapp
    tier: frontend
  annotations:
    submitted-by: enyew-anberbir-ugr9324
    author: "Enyew Anberbir - UGR/9324/12"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp
        ports:
        - containerPort: 80
